
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Luiz Bataioli
 */
public class TelaCadastroClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroClientes
     */
    public TelaCadastroClientes() {
        initComponents();
        habilitarBotoes(false);
        botoesEdicao(false);
        habilitarCaixas(false);
        HabilitarRelatorio();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnCabecalho = new javax.swing.JPanel();
        jlbTitulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnDados = new javax.swing.JPanel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblTelefoneUsuario = new javax.swing.JLabel();
        lblEmailUsuario = new javax.swing.JLabel();
        jtfNomeClienteDigitado = new javax.swing.JTextField();
        jtfTelefoneDigitado = new javax.swing.JTextField();
        jtfEmailClienteDigitado = new javax.swing.JTextField();
        jpnDadosPet = new javax.swing.JPanel();
        jtfIdadePetDigitada = new javax.swing.JTextField();
        jtfNomePetDigitado = new javax.swing.JTextField();
        cbxTipoServico = new javax.swing.JComboBox<>();
        lblTipoServico = new javax.swing.JLabel();
        jtfRacaPetDigitado = new javax.swing.JTextField();
        lblRacaPet = new javax.swing.JLabel();
        jtfTipoPetDigitado = new javax.swing.JTextField();
        lblTipoPet = new javax.swing.JLabel();
        lblNomePet = new javax.swing.JLabel();
        lblIdadePet = new javax.swing.JLabel();
        jspClientesCadastrados = new javax.swing.JScrollPane();
        jtClientesCadastrados = new javax.swing.JTable();
        jpnBotoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnConcluirServico = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnRelatório = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();

        jlbTitulo.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 48)); // NOI18N
        jlbTitulo.setText("Cadastro de Clientes:");

        javax.swing.GroupLayout jpnCabecalhoLayout = new javax.swing.GroupLayout(jpnCabecalho);
        jpnCabecalho.setLayout(jpnCabecalhoLayout);
        jpnCabecalhoLayout.setHorizontalGroup(
            jpnCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCabecalhoLayout.createSequentialGroup()
                .addComponent(jlbTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnCabecalhoLayout.setVerticalGroup(
            jpnCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCabecalhoLayout.createSequentialGroup()
                .addComponent(jlbTitulo)
                .addGap(0, 78, Short.MAX_VALUE))
        );

        jpnDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        lblNomeUsuario.setText("Nome:");

        lblTelefoneUsuario.setText("Telefone:");

        lblEmailUsuario.setText("E-mail:");

        jtfNomeClienteDigitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeClienteDigitadoActionPerformed(evt);
            }
        });

        jpnDadosPet.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Pet"));

        cbxTipoServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banho", "Tosa", "Hospedagem", "Vacinação" }));

        lblTipoServico.setText("Serviço:");

        lblRacaPet.setText("Raça:");

        lblTipoPet.setText("Tipo:");

        lblNomePet.setText("Nome:");

        lblIdadePet.setText("Idade:");

        javax.swing.GroupLayout jpnDadosPetLayout = new javax.swing.GroupLayout(jpnDadosPet);
        jpnDadosPet.setLayout(jpnDadosPetLayout);
        jpnDadosPetLayout.setHorizontalGroup(
            jpnDadosPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDadosPetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDadosPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomePet)
                    .addComponent(lblRacaPet)
                    .addComponent(lblIdadePet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnDadosPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNomePetDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnDadosPetLayout.createSequentialGroup()
                        .addGroup(jpnDadosPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfRacaPetDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnDadosPetLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jtfIdadePetDigitada)))
                        .addGap(18, 18, 18)
                        .addComponent(lblTipoPet)
                        .addGap(18, 18, 18)
                        .addComponent(jtfTipoPetDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipoServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxTipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDadosPetLayout.setVerticalGroup(
            jpnDadosPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDadosPetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDadosPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomePet)
                    .addComponent(jtfNomePetDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnDadosPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoServico)
                    .addGroup(jpnDadosPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRacaPet)
                        .addComponent(jtfRacaPetDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTipoPet)
                        .addComponent(jtfTipoPetDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxTipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpnDadosPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdadePet)
                    .addComponent(jtfIdadePetDigitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnDadosLayout = new javax.swing.GroupLayout(jpnDados);
        jpnDados.setLayout(jpnDadosLayout);
        jpnDadosLayout.setHorizontalGroup(
            jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDadosLayout.createSequentialGroup()
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDadosLayout.createSequentialGroup()
                        .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmailUsuario)
                            .addComponent(lblNomeUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNomeClienteDigitado, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jtfEmailClienteDigitado))
                        .addGap(18, 18, 18)
                        .addComponent(lblTelefoneUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jtfTelefoneDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpnDadosPet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnDadosLayout.setVerticalGroup(
            jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeUsuario)
                    .addComponent(jtfNomeClienteDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefoneUsuario)
                    .addComponent(jtfTelefoneDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailUsuario)
                    .addComponent(jtfEmailClienteDigitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpnDadosPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jpnDados);

        jtClientesCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Telefone", "E-mail", "Atendimento", "Serviço", "Tipo pet", "Nome Pet", "Raça", "Idade", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtClientesCadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClientesCadastradosMouseClicked(evt);
            }
        });
        jtClientesCadastrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtClientesCadastradosKeyReleased(evt);
            }
        });
        jspClientesCadastrados.setViewportView(jtClientesCadastrados);

        jTabbedPane1.addTab("Clientes", jspClientesCadastrados);

        btnSalvar.setText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(75, 45));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(72, 23));
        btnCancelar.setMinimumSize(new java.awt.Dimension(72, 23));
        btnCancelar.setPreferredSize(new java.awt.Dimension(75, 45));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConcluirServico.setText("Concluir");
        btnConcluirServico.setMaximumSize(new java.awt.Dimension(75, 45));
        btnConcluirServico.setPreferredSize(new java.awt.Dimension(75, 45));
        btnConcluirServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirServicoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setPreferredSize(new java.awt.Dimension(75, 45));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.setPreferredSize(new java.awt.Dimension(75, 45));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnRelatório.setText("Relatório");
        btnRelatório.setPreferredSize(new java.awt.Dimension(75, 45));
        btnRelatório.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatórioActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setPreferredSize(new java.awt.Dimension(75, 45));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnBotoesLayout = new javax.swing.GroupLayout(jpnBotoes);
        jpnBotoes.setLayout(jpnBotoesLayout);
        jpnBotoesLayout.setHorizontalGroup(
            jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRelatório, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConcluirServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnBotoesLayout.setVerticalGroup(
            jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConcluirServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelatório, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chiquinho-s.png"))); // NOI18N
        lblLogo.setToolTipText("");
        lblLogo.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpnCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jpnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo)
                    .addComponent(jpnCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        String nomeCliente = jtfNomeClienteDigitado.getText();
        String telefoneCliente = jtfTelefoneDigitado.getText();
        String emailCliente = jtfEmailClienteDigitado.getText();
        String tipoPet = jtfTipoPetDigitado.getText();
        String nomePet = jtfNomePetDigitado.getText();
        String racaPet = jtfRacaPetDigitado.getText();
        String idadePet = jtfIdadePetDigitada.getText();
        String tipoServico = cbxTipoServico.getSelectedItem().toString();
        String status = "Em andamento";
        
        
        
        int resposta = JOptionPane.showConfirmDialog(
               null, 
               "deseja realmente concluir o cadastro de " + nomeCliente + "?", 
               "Conrimação de cadastro", 
               JOptionPane.YES_OPTION);
        
       if(resposta == 0){
           
           DefaultTableModel dtmContatos = (DefaultTableModel) jtClientesCadastrados.getModel();
           Object[] dados = {nomeCliente, telefoneCliente, emailCliente, FormatacaoData(), tipoServico, tipoPet, nomePet, racaPet, idadePet, status};
           dtmContatos.addRow(dados);
           
           JOptionPane.showMessageDialog(null, "O cadastro foi concluído!");
           habilitarBotoes(false);
           habilitarCaixas(false);
           apagarTudo();
           HabilitarRelatorio();
       }else{
           JOptionPane.showMessageDialog(null, "Operação cancelada");
           
       }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jtClientesCadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClientesCadastradosMouseClicked
        if(jtClientesCadastrados.getSelectedRow() != -1){
            
            int resposta = JOptionPane.showConfirmDialog(
               null, 
               "deseja realmente editar algo neste cliente? ", 
               "Confirmação de edição", 
               JOptionPane.YES_NO_OPTION);
            
            if(resposta == JOptionPane.YES_OPTION){
            
                jtfNomeClienteDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 0).toString());
                jtfTelefoneDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 1).toString());
                jtfEmailClienteDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 2).toString());
                cbxTipoServico.setSelectedItem(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 4).toString());
                jtfTipoPetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 5).toString());
                jtfNomePetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 6).toString());
                jtfRacaPetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 7).toString());
                jtfIdadePetDigitada.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 8).toString());
                habilitarBotoes(false);
                botoesEdicao(true);
                habilitarCaixas(true);
                
            }else{
                JOptionPane.showMessageDialog(null, "Operação cancelada!");
            }
            

        }
    }//GEN-LAST:event_jtClientesCadastradosMouseClicked

    private void btnConcluirServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirServicoActionPerformed
        
        if(jtClientesCadastrados.getSelectedRow() != -1){
            
            int resposta = JOptionPane.showConfirmDialog(
               null, 
               "Deseja Concluir o Serviço?", 
               "Conrimação de Gravação", 
               JOptionPane.YES_OPTION);
        
       if(resposta == 0){
           
           jtClientesCadastrados.setValueAt("Finalizado", jtClientesCadastrados.getSelectedRow(), 9);
           botoesEdicao(false);
           habilitarCaixas(false);
           apagarTudo();
           
       }else{
           JOptionPane.showMessageDialog(null, "Cancelada");
       }
            

        }
    }//GEN-LAST:event_btnConcluirServicoActionPerformed

    private void jtClientesCadastradosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtClientesCadastradosKeyReleased
        if(jtClientesCadastrados.getSelectedRow() != -1){
            jtfNomeClienteDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 0).toString());
            jtfTelefoneDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 1).toString());
            jtfEmailClienteDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 2).toString());
            cbxTipoServico.setSelectedItem(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 4).toString());
            jtfTipoPetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 5).toString());
            jtfNomePetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 6).toString());
            jtfRacaPetDigitado.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 7).toString());
            jtfIdadePetDigitada.setText(jtClientesCadastrados.getValueAt(jtClientesCadastrados.getSelectedRow(), 8).toString());
        }
                   
    }//GEN-LAST:event_jtClientesCadastradosKeyReleased

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(jtClientesCadastrados.getSelectedRow() != -1){
            
            DefaultTableModel dtmContatos = (DefaultTableModel) jtClientesCadastrados.getModel();
            
            int resposta = JOptionPane.showConfirmDialog(
               null, 
               "deseja realmente editar este contato?", 
               "Conrimação de salvamento", 
               JOptionPane.YES_OPTION);
        
       if(resposta == 0){
           
            jtClientesCadastrados.setValueAt(jtfNomeClienteDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 0);
            jtClientesCadastrados.setValueAt(jtfTelefoneDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 1);
            jtClientesCadastrados.setValueAt(jtfEmailClienteDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 2);
            jtClientesCadastrados.setValueAt( cbxTipoServico.getSelectedItem(), jtClientesCadastrados.getSelectedRow(), 4);
            jtClientesCadastrados.setValueAt(jtfTipoPetDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 5);
            jtClientesCadastrados.setValueAt(jtfNomePetDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 6);
            jtClientesCadastrados.setValueAt(jtfRacaPetDigitado.getText(), jtClientesCadastrados.getSelectedRow(), 7);
            jtClientesCadastrados.setValueAt(jtfIdadePetDigitada.getText(), jtClientesCadastrados.getSelectedRow(), 8);
            apagarTudo();
            botoesEdicao(false);
            habilitarCaixas(false);
           
           JOptionPane.showMessageDialog(null, "O contato foi editado!");
       }else{
           JOptionPane.showMessageDialog(null, "Cancelada");
       }
            
            
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(jtClientesCadastrados.getSelectedRow() != -1){
            
            int resposta = JOptionPane.showConfirmDialog(
               null, 
               "deseja realmente excluir esse contato?", 
               "Confirmação de exclusão", 
               JOptionPane.YES_OPTION);
            
            if(resposta == 0){
            
            DefaultTableModel dtmContatos = (DefaultTableModel) jtClientesCadastrados.getModel();
            dtmContatos.removeRow(jtClientesCadastrados.getSelectedRow());
            JOptionPane.showMessageDialog(null, "Cliente excluido com sucesso!");
                botoesEdicao(false);
                habilitarCaixas(false);
                apagarTudo();
                HabilitarRelatorio();
            }else{
                JOptionPane.showMessageDialog(null, "Operação cancelada!");
            }
            
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        habilitarBotoes(true);
        habilitarCaixas(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnRelatórioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatórioActionPerformed

        DefaultTableModel model = (DefaultTableModel) jtClientesCadastrados.getModel();

        int rowCount = model.getRowCount();
        int colCount = model.getColumnCount();

        StringBuilder content = new StringBuilder();

        for (int i = 0; i < rowCount; i++) {
            for (int j = 0; j < colCount; j++) {
                content.append(model.getValueAt(i, j));
                content.append("\t"); 
            }
            content.append("\n"); 
            
        }

        try (PrintWriter writer = new PrintWriter(new FileWriter("C:\\Users\\marce\\Documents\\Java\\Chiquinhos\\rel.txt"))) {
            writer.println(content.toString());
            JOptionPane.showMessageDialog(null, "Relatório gerado com sucesso!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Relatório não foi gerado! Verifique a pasta de destino no código!");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnRelatórioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        apagarTudo();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jtfNomeClienteDigitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeClienteDigitadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeClienteDigitadoActionPerformed

    private void apagarTudo(){
        jtfEmailClienteDigitado.setText("");
        jtfIdadePetDigitada.setText("");
        jtfNomeClienteDigitado.setText("");
        jtfNomePetDigitado.setText("");
        jtfRacaPetDigitado.setText("");
        jtfTelefoneDigitado.setText("");
        jtfTipoPetDigitado.setText("");
        
    }
    
    private void habilitarBotoes(boolean setReset){
        btnCancelar.setEnabled(setReset);
        btnSalvar.setEnabled(setReset);
    }
    
    private void botoesEdicao(boolean setReset){
        btnConcluirServico.setEnabled(setReset);
        btnEditar.setEnabled(setReset);
        btnExcluir.setEnabled(setReset);
    }
    private void habilitarCaixas(boolean setReset){
        jtfEmailClienteDigitado.setEditable(setReset);
        jtfIdadePetDigitada.setEditable(setReset);
        jtfNomeClienteDigitado.setEditable(setReset);
        jtfNomePetDigitado.setEditable(setReset);
        jtfRacaPetDigitado.setEditable(setReset);
        jtfTelefoneDigitado.setEditable(setReset);
        jtfTipoPetDigitado.setEditable(setReset);
        cbxTipoServico.setEnabled(setReset);
    }
    
    private String FormatacaoData() {
        
        Date dataAtual = new Date();

        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        String dataFormatada = formato.format(dataAtual);

        return(dataFormatada);
    
}
    
    private void HabilitarRelatorio(){
        if(jtClientesCadastrados.getRowCount()>0){
            btnRelatório.setEnabled(true);
        }else{
            btnRelatório.setEnabled(false);
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConcluirServico;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRelatório;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxTipoServico;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JPanel jpnBotoes;
    private javax.swing.JPanel jpnCabecalho;
    private javax.swing.JPanel jpnDados;
    private javax.swing.JPanel jpnDadosPet;
    private javax.swing.JScrollPane jspClientesCadastrados;
    private javax.swing.JTable jtClientesCadastrados;
    private javax.swing.JTextField jtfEmailClienteDigitado;
    private javax.swing.JTextField jtfIdadePetDigitada;
    private javax.swing.JTextField jtfNomeClienteDigitado;
    private javax.swing.JTextField jtfNomePetDigitado;
    private javax.swing.JTextField jtfRacaPetDigitado;
    private javax.swing.JTextField jtfTelefoneDigitado;
    private javax.swing.JTextField jtfTipoPetDigitado;
    private javax.swing.JLabel lblEmailUsuario;
    private javax.swing.JLabel lblIdadePet;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNomePet;
    private javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JLabel lblRacaPet;
    private javax.swing.JLabel lblTelefoneUsuario;
    private javax.swing.JLabel lblTipoPet;
    private javax.swing.JLabel lblTipoServico;
    // End of variables declaration//GEN-END:variables
}
